export { default as IconCategory } from "./category";
export { default as IconCustomer } from "./customer";
export { default as IconDashboard } from "./dashboard";
export { default as IconLogout } from "./logout";
export { default as IconOrder } from "./order";
export { default as IconProduct } from "./product";
export { default as IconSetting } from "./setting";
export { default as IconNotification } from "./notification";
export { default as IconStaff } from "./staff";
